// Generated by deno task convert

import type { WEBVIEW2_FUNCS } from './webview2.d.ts';

export const params: WEBVIEW2_FUNCS = {
  _CreateCoreWebView2Environment: {
    parameters: ['pointer', 'function'],
    result: 'i32',
  },
  _CreateCoreWebView2EnvironmentWithOptions: {
    parameters: ['pointer', 'pointer', 'pointer', 'pointer', 'function'],
    result: 'i32',
  },
  _CompareBrowserVersions: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  _GetAvailableCoreWebView2BrowserVersionString: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  CreateWebView2Connector: {
    parameters: ['pointer'],
    result: 'pointer',
  },
  SetWebview2Environment: {
    parameters: ['pointer', 'pointer'],
    result: 'pointer',
  },
  InitSettings: {
    parameters: ['pointer'],
    result: 'pointer',
  },
  InitControllers: {
    parameters: ['pointer', 'pointer'],
    result: 'pointer',
  },
  CreateCoreWebView2Controller: {
    parameters: ['pointer', 'pointer', 'function'],
    result: 'i32',
  },
  get_IsScriptEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsScriptEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_IsWebMessageEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsWebMessageEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_AreDefaultScriptDialogsEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_AreDefaultScriptDialogsEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_IsStatusBarEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsStatusBarEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_AreDevToolsEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_AreDevToolsEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_AreDefaultContextMenusEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_AreDefaultContextMenusEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_AreHostObjectsAllowed: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_AreHostObjectsAllowed: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_IsZoomControlEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsZoomControlEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_IsBuiltInErrorPageEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsBuiltInErrorPageEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_UserAgent: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_UserAgent: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  get_AreBrowserAcceleratorKeysEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_AreBrowserAcceleratorKeysEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_IsPasswordAutosaveEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsPasswordAutosaveEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_IsGeneralAutofillEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsGeneralAutofillEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_IsPinchZoomEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsPinchZoomEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_IsSwipeNavigationEnabled: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsSwipeNavigationEnabled: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  add_AcceleratorKeyPressed: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_AcceleratorKeyPressed: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  get_Bounds: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_Bounds: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  Close: {
    parameters: ['pointer'],
    result: 'i32',
  },
  get_CoreWebView2: {
    parameters: ['pointer'],
    result: 'i32',
  },
  add_GotFocus: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_GotFocus: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  get_IsVisible: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_IsVisible: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  add_LostFocus: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_LostFocus: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  MoveFocus: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  add_MoveFocusRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_MoveFocusRequested: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  NotifyParentWindowPositionChanged: {
    parameters: ['pointer'],
    result: 'i32',
  },
  get_ParentWindow: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_ParentWindow: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  SetBoundsAndZoomFactor: {
    parameters: ['pointer', 'buffer', 'f64'],
    result: 'i32',
  },
  get_ZoomFactor: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_ZoomFactor: {
    parameters: ['pointer', 'f64'],
    result: 'i32',
  },
  add_ZoomFactorChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_ZoomFactorChanged: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  get_DefaultBackgroundColor: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_DefaultBackgroundColor: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  add_RasterizationScaleChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_RasterizationScaleChanged: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  get_BoundsMode: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_BoundsMode: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_RasterizationScale: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_RasterizationScale: {
    parameters: ['pointer', 'f64'],
    result: 'i32',
  },
  get_ShouldDetectMonitorScaleChanges: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_ShouldDetectMonitorScaleChanges: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  get_AllowExternalDrop: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  put_AllowExternalDrop: {
    parameters: ['pointer', 'i32'],
    result: 'i32',
  },
  CallDevToolsProtocolMethod: {
    parameters: ['pointer', 'pointer', 'pointer', 'function'],
    result: 'i32',
  },
  GetDevToolsProtocolEventReceiver: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  OpenDevToolsWindow: {
    parameters: ['pointer'],
    result: 'i32',
  },
  add_DocumentTitleChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_DocumentTitleChanged: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  get_DocumentTitle: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  add_HistoryChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_HistoryChanged: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  PostWebMessageAsJson: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  PostWebMessageAsString: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  add_WebMessageReceived: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_WebMessageReceived: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  Navigate: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  add_NavigationCompleted: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_NavigationCompleted: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  add_NavigationStarting: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_NavigationStarting: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  NavigateToString: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  add_FrameNavigationCompleted: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_FrameNavigationCompleted: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  add_FrameNavigationStarting: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_FrameNavigationStarting: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  add_PermissionRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_PermissionRequested: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  add_ScriptDialogOpening: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_ScriptDialogOpening: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  AddScriptToExecuteOnDocumentCreated: {
    parameters: ['pointer', 'pointer', 'function'],
    result: 'i32',
  },
  RemoveScriptToExecuteOnDocumentCreated: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  ExecuteScript: {
    parameters: ['pointer', 'pointer', 'function'],
    result: 'i32',
  },
  AddHostObjectToScript: {
    parameters: ['pointer', 'pointer', 'pointer'],
    result: 'i32',
  },
  RemoveHostObjectFromScript: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  get_Source: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  add_SourceChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_SourceChanged: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  Reload: {
    parameters: ['pointer'],
    result: 'i32',
  },
  get_CanGoBack: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  get_CanGoForward: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  GoBack: {
    parameters: ['pointer'],
    result: 'i32',
  },
  GoForward: {
    parameters: ['pointer'],
    result: 'i32',
  },
  Stop: {
    parameters: ['pointer'],
    result: 'i32',
  },
  add_ContentLoading: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_ContentLoading: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  add_ProcessFailed: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_ProcessFailed: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  get_Settings: {
    parameters: ['pointer'],
    result: 'i32',
  },
  CapturePreview: {
    parameters: ['pointer', 'i32', 'pointer', 'function'],
    result: 'i32',
  },
  get_BrowserProcessId: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  add_NewWindowRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_NewWindowRequested: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  add_ContainsFullScreenElementChanged: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_ContainsFullScreenElementChanged: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  get_ContainsFullScreenElement: {
    parameters: ['pointer', 'pointer'],
    result: 'i32',
  },
  add_WebResourceRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_WebResourceRequested: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
  AddWebResourceRequestedFilter: {
    parameters: ['pointer', 'pointer', 'i32'],
    result: 'i32',
  },
  RemoveWebResourceRequestedFilter: {
    parameters: ['pointer', 'pointer', 'i32'],
    result: 'i32',
  },
  add_WindowCloseRequested: {
    parameters: ['pointer', 'function', 'pointer'],
    result: 'i32',
  },
  remove_WindowCloseRequested: {
    parameters: ['pointer', 'buffer'],
    result: 'i32',
  },
};
